### ISSUE TITLE
Auto-format documentation

### ISSUE THREAD

**Issue by joe-sharp** [toreriklinnerud/sublime-rubyfmt#1]
There were some issue in the documentation compared to what I saw/had. I am on Mac version of ST3.

• I found that auto-format was on by default, I had to override it. Here are the settings-defaults:
```json
{
  "ruby_executable": "ruby",
  "rubyfmt_executable": "rubyfmt",
  "format_on_save": true,
}
```

• The setting format is different for me:
```json
{ "format_on_save": false }
```

**Comment by toreriklinnerud** [comment]
Thanks for letting me know, I’ll update the default to be in line with what it says in the readme.

**Comment by toreriklinnerud** [comment]
I updated the readme to reflect the default setting. https://github.com/toreriklinnerud/sublime-rubyfmt/commit/b0a22191208623b8f0585630e6388e22469709de
